apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: driv/buildpack-playground-java-api:b4.20240709.071826 # {"$imagepolicy": "flux-system:buildpack-playground-java-api"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
