apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  interval: 15m
  chart:
    spec:
      interval: 10m
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    controller:
      metrics:
        enabled: true
      podAnnotations:
        "prometheus.io/scrape": true
        "prometheus.io/port": 10254
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flagger
  namespace: ingress-nginx
spec:
  interval: 1h
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: ingress-nginx
spec:
  releaseName: flagger
  interval: 15m
  chart:
    spec:
      interval: 10m
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  values:
    prometheus:
      install: true
    meshProvider: nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: test
spec:
  releaseName: flagger
  interval: 15m
  chart:
    spec:
      interval: 10m
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: flagger
