apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: response-duration
  namespace: default
spec:
  provider:
    type: prometheus
    address: http://flagger-prometheus.ingress-nginx:9090
  query: |
    sum(
        rate(
          nginx_ingress_controller_response_duration_seconds_sum{
            namespace="{{ namespace }}",
            ingress="{{ ingress }}",
            canary!=""
          }[{{ interval }}]
        )
      ) 
      / 
      sum(
        rate(
          nginx_ingress_controller_response_duration_seconds_sum{
            namespace="{{ namespace }}",
            ingress="{{ ingress }}",
            canary!=""
          }[{{ interval }}]
        )
      ) 
      * 1000