apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
    spec:
      containers:
        - name: nodejs
          image: driv/buildpack-playground-nodejs-frontend:b22.20240714.201835 # {"$imagepolicy": "flux-system:buildpack-playground-nodejs-frontend"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
