apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted
  namespace: default
spec:
  selector:
    matchLabels:
      app: fronted
  template:
    metadata:
      labels:
        app: fronted
    spec:
      containers:
        - name: nodejs
          image: driv/buildpack-playground-nodejs-frontend:b1.20240703.065754 # {"$imagepolicy": "flux-system:buildpack-playground-nodejs-frontend"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
