apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: golang-api
  namespace: default
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-api
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: number-generator
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: http
  analysis:
    interval: 10s
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    # NGINX Prometheus checks
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: response-duration
      templateRef:
        name: response-duration
        namespace: default
      interval: 1m
      thresholdRange:
        max: 100
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.test/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -f http://golang-api-canary.default.svc.cluster.local./status"
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 https://www.172-18-0-3.nip.io/next-number?number=10"