apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: driv/buildpack-playground-golang-api:b35.20240807.064259 # {"$imagepolicy": "flux-system:buildpack-playground-golang-api"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4444
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
              cpu: "1"
            requests:
              memory: 100Mi
              cpu: 100m
